pragmint:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: localhost
      port: 10000
      schema: default
      user: # leave blank unless you've set up authentication
      pass: # leave blank unless you've set up authentication
      use_ssl: False