pragmint:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: default
      host: localhost
      port: 10000
      user: # leave this blank if no user authentication is required
      auth: # leave this blank if no authentication is required
      kerberos_service_name: # leave this blank if not using Kerberos
      use_ssl: false