name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Start Docker service
      run: sudo service docker start

    - name: Verify Docker is running
      run: docker info

    - name: Start Spark Cluster
      run: make spark-up

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies and create virtual environment
      run: |
        make uv && make venv

    - name: Test dbt
      run: |
        source .venv/bin/activate
        dbt debug
